apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-app-demo
spec:
  selector:
    matchLabels:
      app: vault-app-demo
  replicas: 1
  template:
    metadata:
      spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/helloworld"
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "secret/helloworld" -}}
          {
            "username" : "{{ .Data.username }}",
            "password" : "{{ .Data.password }}"
          }
          {{- end }}
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-payment-api: "secret/payment-api"
        vault.hashicorp.com/agent-inject-template-payment-api: |
          {{- with secret "secret/payment-api" -}}
          # payment gw api key
          {
            "APIKEY" : "{{ .Data.APIKEY }}"
          }
          {{- end }}
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-sendmail-api: "secret/sendmail-api"
        vault.hashicorp.com/agent-inject-template-sendmail-api: |
          {{- with secret "secret/sendmail-api" -}}
          # smtp relay api key
          {
            "APIKEY" : "{{ .Data.APIKEY }}"
          }
          {{- end }}
        vault.hashicorp.com/role: "myapp"
      labels:
        app: vault-app-demo
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: jweissig/app:0.0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app: vault-app-demo