apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1

  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-database-connect.sh: "database/creds/mysql-role"
        vault.hashicorp.com/agent-inject-template-database-connect.sh: |
          {{- with secret "database/creds/mysql-role" -}}
          mysql -h my-release-mysql.default.svc.cluster.local --user={{ .Data.username }} --password={{ .Data.password }} my_database

          {{- end -}}
    spec:
      serviceAccountName: test-app
      containers:
        - name: test-app
          image: jweissig/app:0.0.1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app
  labels:
    app: test-app

